version: "3.9"
services:
  # DB 컨테이너 (미리 데이터가 들어있는 이미지)
  db:
    image: kangyejini/cookrep_db:test1  # 미리 데이터가 들어 있는 DB 이미지
    container_name: cookrepsql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: ${TZ}
    ports:
      - "3377:3306"   # 로컬에서 Workbench 등으로 접속할 포트
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${DB_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql           # DB 데이터 영속화
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # 초기 SQL 실행
    restart: unless-stopped
    networks:
      - cookrep-net

  # Java 앱 컨테이너
  app:
    image: kihyun1232/cookrep:app7  # Java 앱 이미지
    container_name: cookrep-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      OPEN_API_KEY: ${OPEN_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
      LANG: ${LANG}
      LC_ALL: ${LC_ALL}
      TZ: ${TZ}
    ports:
      - "8082:8080"
    stdin_open: true    # CLI 기반 앱 입력 가능
    tty: true           # 터미널 출력 가능
    networks:
      - cookrep-net

volumes:
  db_data:

networks:
  cookrep-net:
    driver: bridge
